### PR TITLE
Documents request page

### PR DESCRIPTION
**Pull request by KaiKai-dev**
changes:
- added file upload modal
- auto compute age based on birthdate
- upload requirements modal
- uploded requirements count checker

bugs found:
- when closing the upload modal to change documents, the changes do not reflect on the upload modal

### CODE REVIEW

**Comment by dongumayagay** [comment]
@KaiKai-dev bat mukha pading input yung sa age if di na gagamitin?

**Comment by KaiKai-dev** [comment]
> @KaiKai-dev bat mukha pading input yung sa age if di na gagamitin?

ay oo nga no, baguhin ko nlng style

**Comment by KaiKai-dev** [comment]
fixed bug:
- when closing the upload modal to change documents, the changes do not reflect on the upload modal

bugs found:
- age doesn't auto-compute again after clearing the form

**Comment by KaiKai-dev** [comment]
@dongumayagay tinry ko ilagay yung files galing sa upload file component papuntang requirementsFIles na nasa page.svelte, pareview nlng kung may mali, salamats

**Comment by KaiKai-dev** [comment]
@dongumayagay naka console.log na rin yung laman nung array ng files, tanggalin ko nlng yung console.log pag okay na sya

**Comment by dongumayagay** [comment]
> @dongumayagay naka console.log na rin yung laman nung array ng files, tanggalin ko nlng yung console.log pag okay na sya

so malapit na maayos or goods nam?

**Comment by KaiKai-dev** [comment]
> > @dongumayagay naka console.log na rin yung laman nung array ng files, tanggalin ko nlng yung console.log pag okay na sya
> 
> so malapit na maayos or goods nam?

@dongumayagay okay naman na sya, ilalagay nlng sa database

**Review by dongumayagay — APPROVED** [review]

**Pull request merged**
